### ISSUE TITLE
Venom gets loaded after native lsp client

### ISSUE THREAD

**Issue by GordianDziwis** [rafi/vim-venom#6]
I am using the vim version of vim-venom.

I need to restart the native lsp client, to get an environment working. This issue does not exist when I start nvim from a terminal, where the environment is already activated. My guess is that the lsp client gets initiated before, venom activates the environment.

**Comment by rafi** [comment]
Please see https://github.com/rafi/neoconf-venom.nvim which properly sets LSP servers options, this plugin is no longer maintained.
